title: Page

create:
  redirect: true
  status: unlisted

options:
  move: false

image:
  icon: page
  query: false

columns:
  main:
    width: 3/4
    sections:
      intro:
        label: false
        type: fields
        fields:
          description:
            label: Introduction text
            placeholder: Text …
            type: writer
            marks:
              - bold
              - italic
              - underline
              - strike
              - link
              - clear
            nodes: false
          text:
            label: Additional text
            placeholder: Text …
            type: writer
            marks:
              - bold
              - italic
              - underline
              - strike
              - link
              - clear
            nodes: false
      cover:
        label: false
        type: fields
        fields:
          cover:
            label: Cover image
            type: layout
            layouts:
              - "1/4, 1/4, 1/4, 1/4"
              - "1/2, 1/2"
              - "1/2, 1/4, 1/4"
              - "1/4, 1/4, 1/2"
              - "3/4, 1/4"
              - "1/4, 3/4"
            fieldsets:
              - textitem
              - galleryitem
      gallery:
        label: false
        type: fields
        fields:
          grid:
            label: Gallery
            type: layout
            layouts:
              - "1/4, 1/4, 1/4, 1/4"
              - "1/2, 1/2"
              - "1/2, 1/4, 1/4"
              - "1/4, 1/4, 1/2"
              - "3/4, 1/4"
              - "1/4, 3/4"
            fieldsets:
              - textitem
              - galleryitem
  sidebar:
    width: 1/4
    sections:
      features:
        label: false
        type: fields
        fields:
          attachments:
            label: Attachments
            type: files
            help: Upload here the pdf files you want to use as attachments on this page.
            template: document
            uploads: document
            query: page.files.filterBy("type", "document")
            link: false
            image:
              ratio: 4/3
              cover: true

