title: Project

create:
  title:
    label: Project name
  fields:
    - category
  redirect: true
  status: unlisted

options:
  move: false

image:
  icon: false

columns:
  main:
    width: 2/3
    sections:
      content:
        label: false
        type: fields
        fields:
          gallery:
            label:
              en: Gallery
              it: Galleria immagini
            type: files
            multiple: true
            translate: false
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true
          galleryInfo:
            type: info
            label: false
            text: >
                The first two images appear on the page {{ page.parent.title }}.
          description:
            label: Information
            type: writer
            marks:
              - bold
              - italic
              - underline
              - strike
              - link
              - clear
            nodes: false
  sidebar:
    width: 1/3
    sections:
      features:
        label: false
        type: fields
        fields:
          year: 
            label: Year
            type: tags
            max: 1
            layout: list
            options: query
            query:
              fetch: page.siblings.pluck("year", ",", true)
              text: "{{ arrayItem.value }}"
              value: "{{ arrayItem.value }}"
          client: 
            label: Client
            type: tags
            max: 1
            layout: list
            options: query
            query:
              fetch:  page.siblings.pluck("client", ",", true)
              text: "{{ arrayItem.value }}"
              value: "{{ arrayItem.value }}"
          location: 
            label: Location
            type: tags
            max: 1
            layout: list
            options: query
            query:
              fetch:  page.siblings.pluck("location", ",", true)
              text: "{{ arrayItem.value }}"
              value: "{{ arrayItem.value }}"
          category: 
            label: Category
            type: tags
            max: 1
            layout: list
            options: query
            query:
              fetch:  page.siblings.pluck("category", ",", true)
              text: "{{ arrayItem.value }}"
              value: "{{ arrayItem.value }}"
          stat: 
            label: Status
            type: tags
            max: 1
            layout: list
            options: query
            query:
              fetch:  page.siblings.pluck("status", ",", true)
              text: "{{ arrayItem.value }}"
              value: "{{ arrayItem.value }}"
          attachments:
            label:
              en: File attachments
              it: File allegati          
            type: files 
            template: files
            uploads: files
            multiple: true
            translate: false
            image:
              icon: true
              ratio: 4/3
              back: white
              cover: true


