columns:
  main:
    width: 3/4
    sections:
      elements:
        label: false
        type: fields
        fields:
          grid:
            label: Build the {{ page.title }} page
            type: layout
            layouts:
              - "1/1"
              - "1/4, 1/4, 1/4, 1/4"
              - "1/2, 1/2"
              - "1/2, 1/4, 1/4"
              - "1/4, 1/4, 1/2"
              - "1/4, 1/2, 1/4"
              - "3/4, 1/4"
              - "1/4, 3/4"
            fieldsets:
              - introblock
              - textblock
              - summaryblock
              - galleryblock
  sidebar:
    width: 1/4
    sections:
      features:
        label: false
        type: fields
        fields:
          attachments: fields/attachments