title: Default

sections:
  address:
    type: fields
    fields:
      name:
        label: First Name
        type: text
        width: 1/2
        placeholder: First Name  
        translate: false
        validate:
          minLength: 3
          maxLength: 160
      surname:
        label: Last Name
        type: text
        width: 1/2
        placeholder: Last Name
        translate: false
        validate:
          minLength: 3
          maxLength: 160