title: Default

sections:
  address:
    type: fields
    fields:
      name:
        label:
          en: First Name
          it: Nome
        type: text
        width: 1/2
        placeholder:
          en: First Name
          it: Nome    
        translate: false
        validate:
          minLength: 3
          maxLength: 160
      surname:
        label:
          en: Last Name
          it: Cognome
        type: text
        width: 1/2
        placeholder:
          en: Last Name
          it: Cognome 
        translate: false
        validate:
          minLength: 3
          maxLength: 160
      organization:
        label:
          en: Organization
          it: Organizzazione
        type: text
        width: 1/2
        translate: false
        validate:
          maxLength: 160