title: Site

tabs:
  website:
    label: Website
    icon: angle-right
    columns:
      main:
        width: 3/4
        sections:
          pagesHeadline:
            type: fields
            fields:
              pagesHeadline:
                type: headline
                label: Main pages
          pages:
            label: Pages
            type: pages
            template:
              - page
              - projects
              - home
            info: "Template: {{ page.template.name() }}"
            help: When a page is listed, it appears as a link in the main navigation menu at the top of the page. The homepage ({{ site.find("home").title }}) is always listed, even in maintenance mode.
          header:
            type: fields
            fields:
              lineA:
                type: line
              headerHeadline:
                label: Header
                type: headline
              subtitle:
                label: Website subtitle
                width: 1/4
                type: text
              contactname:
                label: Contact label
                width: 1/4
                type: text
                help: The menu label for contact.
          footer:
            type: fields
            fields:
              lineB:
                type: line
              footerHeadline:
                type: headline
                label: Footer
              contactheadline:
                label: Headline
                width: 1/4
                type: text
              contact:
                label: Contact (max. 4 elements)
                width: 3/4
                type: blocks
                max: 4
                fieldsets:
                  - contacblock
          footermenu:
            label: Footer menu
            type: pages
            parent: site.find("appendix")
            templates: appendix
            help: When a page is listed, it appears as a link in the footer navigation menu at the bottom of the page.
      sidebar:
        width: 1/4
        sections:
          settings: 
            type: fields
            fields:
              settingsHeadline:
                type: headline
                label: Settings
              lowercase:
                label: false
                type: toggle
                text: Make all labels lowercase?
                help: This switcher will make all labels lowercase (e.g., menu labels, buttons, contact links), regardless of how they are written.
              setHomePage:
                label: Launch your website / Maintenance mode
                type: pages
                max: 1
                link: false
                subpages: false
                query: site.children.filterBy('template', 'wip')
                help: Deselect the "Under Construction" page when you are ready to launch your website. Select the "Under Construction" page again whenever you need to put your website into maintenance mode.
  seo:
    label: Website metadata
    icon: angle-right
    columns:
      main:
        width: 1/2
        sections:
          seocontent:
            type: fields
            fields:
              description:
                label: Description
                type: textarea
                buttons: false
              keywords:
                label: Keywords
                type: tags         
      image:
        width: 1/2
        sections:
          image:
            type: fields
            fields:
              ogimage:
                label: Open Graph Image
                type: files
                template: file
                uploads: file
                layout: cards
                size: full
                multiple: false
                image:
                  ratio: 4/3
                  cover: true
                help: An Open Graph image is the picture that shows up when you share a link on social media.