title: Site

tabs:
  website:
    label: Website
    icon: angle-right
    columns:
      main:
        width: 3/4
        sections:
          pages:
            label: false
            type: pages
            template:
              - home
              - works
              - page
            help: When a page is listed, it appears in the main navigation menu.
          otherPages:
            label: Other pages
            type: pages
            template:
              - default
            help: When a page is listed, it appears in the footer at the bottom of the page.
          footer:
            type: fields
            fields:
              contact:
                label: Footer and contact
                type: blocks
                fieldsets:
                  - contactitem
      sidebar:
        width: 1/4
        sections:
          headline: 
            type: fields
            fields:
              subtitle:
                label: Website subtitle
                type: text
                help: The label on the left of the header.
              contactname:
                label: Contact
                type: text
                help: The menu label for contact.
  seo:
    label: Website metadata
    icon: angle-right
    columns:
      main:
        width: 1/2
        sections:
          seocontent:
            type: fields
            fields:
              description:
                label: Description
                type: textarea
                buttons: false
              keywords:
                label: 
                  en: Keywords
                  it: Parole chiave
                type: tags         
      image:
        width: 1/2
        sections:
          image:
            type: fields
            fields:
              ogimage:
                label: Open Graph Image
                type: files
                template: file
                uploads: file
                layout: cards
                size: full
                multiple: false
                image:
                  ratio: 4/3
                  cover: true
                help: An Open Graph image is the picture that shows up when you share a link on social media.