title: Site

tabs:
  website:
    label: Website
    icon: angle-right
    columns:
      main:
        width: 3/4
        sections:
          pagesHeadline:
            type: fields
            fields:
              pagesHeadline:
                type: headline
                label: Main pages
          pages:
            label: false
            type: pages
            template:
              - home
              - works
              - page
            help: When a page is listed, it appears as a link in the main navigation menu at the top of the page.
          footerHeadline:
            type: fields
            fields:
              footerHeadline:
                type: headline
                label: Footer
          footer:
            type: fields
            fields:
              contact:
                label: Contact (max. 4 items)
                type: blocks
                max: 4
                fieldsets:
                  - contactitem
          footermenu:
            label: Footer menu
            type: pages
            template:
              - simple
            help: When a page is listed, it appears as a link in the footer navigation menu at the bottom of the page.
      sidebar:
        width: 1/4
        sections:
          header: 
            type: fields
            fields:
              headerHeadline:
                type: headline
                label: Header
              subtitle:
                label: Website subtitle
                type: text
              contactname:
                label: Contact
                type: text
                help: The menu label for contact.
              lowercase:
                label: false
                type: toggle
                text: Make all labels lowercase?
                # default: true
                help: This will make all links in the header and footer lowercase, regardless of how they are written in the page titles.
  seo:
    label: Website metadata
    icon: angle-right
    columns:
      main:
        width: 1/2
        sections:
          seocontent:
            type: fields
            fields:
              description:
                label: Description
                type: textarea
                buttons: false
              keywords:
                label: Keywords
                type: tags         
      image:
        width: 1/2
        sections:
          image:
            type: fields
            fields:
              ogimage:
                label: Open Graph Image
                type: files
                template: file
                uploads: file
                layout: cards
                size: full
                multiple: false
                image:
                  ratio: 4/3
                  cover: true
                help: An Open Graph image is the picture that shows up when you share a link on social media.